# Generated by Django 5.0.4 on 2024-04-04 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(max_length=1024)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('comida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='menu.comida')),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'db_table': 'Videos',
            },
        ),
    ]
