# Generated by Django 5.0.4 on 2024-04-04 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('ID_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre_categoria', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('ID_comida', models.BigAutoField(primary_key=True, serialize=False)),
                ('Descripcion_comida', models.TextField()),
                ('Nombre_comida', models.CharField(max_length=255)),
                ('Precio_comida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Categoria', models.ForeignKey(db_column='ID_categoria', on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='menu.categoria')),
            ],
            options={
                'verbose_name_plural': 'Comidas',
                'db_table': 'Comidas',
            },
        ),
    ]
