# Generated by Django 5.0.4 on 2024-04-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_comida_descripcion_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Nombre_categoria',
            field=models.TextField(unique=True),
        ),
    ]
