# Generated by Django 5.0.4 on 2024-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='Descripcion_comida',
            field=models.TextField(null=True),
        ),
    ]
