name: Backend CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'Backend/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'Backend/**'

jobs:
  backend-test-and-lint:
    runs-on: ubuntu-latest
    services:
      postgres:  # This is the service name and what DATABASE_HOST should refer to
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    strategy:
      matrix:
        python-version: [3.10.11]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      - name: Set up test database environment variables
        run: |
          echo "DATABASE_HOST=postgres" >> $GITHUB_ENV
          echo "DATABASE_NAME=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "DATABASE_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "DATABASE_PORT=5432" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          cd Backend
          python manage.py test

      - name: Lint with flake8
        run: |
          flake8 Backend --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Coverage Report
        run: |
          cd Backend
          coverage run manage.py test
          coverage report
