name: Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout the code

      - name: Set up Python 3  # Setup Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Set up Node.js  # Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '21'
    
      - name: Install backend dependencies  # Install backend Python dependencies
        run: pip install -r Backend/requirements.txt

      - name: Install frontend dependencies  # Install frontend Node dependencies
        run: |
          cd frontend
          npm install

      - name: Run tests  # Run backend tests
        run: |
          cd Backend
          python manage.py test

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the code again for Docker build

      - name: Log in to Docker Hub  # Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image  # Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
