name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r Backend/requirements.txt

      - name: Run tests
        run: |
          cd Backend
          python manage.py test --noinput

      - name: Disconnect Idle Connections Before Teardown
        run: |
          psql "host=${{ secrets.POSTGRES_HOST }} dbname=${{ secrets.POSTGRES_DATABASE }} user=${{ secrets.POSTGRES_USER }} password=${{ secrets.POSTGRES_PASSWORD }} sslmode=require" -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '${{ secrets.POSTGRES_DATABASE }}_test' AND state = 'idle';"
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Verify Database Closure
        run: |
          if ! pg_isready -h ${{ secrets.POSTGRES_HOST }} -U ${{ secrets.POSTGRES_USER }}; then
            echo "Database is not ready, might be closed already."
          else
            echo "Database is still running, needs further checking."
          fi
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}






  build-and-push-backend:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3  # Checkout the repository content again for backend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Use DOCKER_HUB_USERNAME secret for Docker Hub login
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Use DOCKER_HUB_ACCESS_TOKEN secret for Docker Hub password

      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:backend-latest
          push: true

  build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push-backend
    steps:
      - uses: actions/checkout@v3  # Checkout repository again for frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:frontend-latest
          push: true
